### ISSUE TITLE
NPM start fails to compile in this project.

### ISSUE THREAD

**Issue by ViktorHSN** [izaera/liferay-js-toolkit-showcase#2]
Hello,
I´ve tried to run this project with npm run and it gives me the following compile error:

![image](https://user-images.githubusercontent.com/7051143/68389044-c7369800-0140-11ea-835e-51f32e0f20b6.png)

Nothing was changed in configurations file nor in the code.

**Comment by izaera** [comment]
Hi @ViktorHSN 

The projects are provided for learning purposes and they are supposed to be deployed to Liferay Portal, not run standalone.

If you specifically need that functionality for anything I can provide some help if you want to investigate how to fix it.

Thx :-)

**Comment by ViktorHSN** [comment]
Yes, I would love that functionality but have no clue where to start investigating this.

**Comment by izaera** [comment]
Why do you need that in this specific project? I mean, I could understand you need it in any of **your** projects, but not these, that are supposed to be useful for learning purposes only... :thinking: 

If you need it for any of your projects and it doesn't work, the proper place to report that would be https://github.com/liferay/liferay-js-toolkit, which is the real project where the tools used here are maintained...

**Comment by ViktorHSN** [comment]
I am trying to export my react component to my companies liferay portal, but I am getting an error with the build, i am running it locally in a webpack bundle, it works ok, but during the build process, it just fails. What I am trying to do is import my component into this project and see if it works, but first, i would like to run it locally to see if everything is ok.

**Comment by ViktorHSN** [comment]
In this project, Where is the configuration file that sets the jar´s name?

**Comment by izaera** [comment]
In that case, I would suggest using the official Liferay support channels: the community slack, message boards, or support if you have a contract...

This is project is maintained by me personally (it's not part of Liferay organization) and I cannot give you support you from here because I don't have time to do it. 

Sorry :-(.

Regarding your question, take a look at the docs -> https://github.com/liferay/liferay-js-toolkit/wiki/.npmbundlerrc-file-reference#create-jaroutput-filename
