### ISSUE TITLE
React portlet with webpack and not using liferay-npm-bundler

### ISSUE THREAD

**Issue by deepakpoilil** [izaera/liferay-js-toolkit-showcase#4]
Hi,
We are using liferay 7.2, with pure JavaScript react portlet created using liferay JS toolkit. due to some of the 3rd party dependency our final jar file having size around 250 MB. Since we are using only one portlet per page, can you provide the configuration or details to create react portlet with web pack and not using liferay bundler.

Regards
Deepak P

**Comment by izaera** [comment]
Unfortunately not. This project is maintained by me as a private user, not as a Liferay member (that's why it is at `izaera` instead of `liferay` user). 

Also, it is intended to learn how to use the JS Toolkit, not to showcase other tools.

However, we are [adding a new option to the JS Toolkit to increase the JAR compression level](https://github.com/liferay/liferay-frontend-projects/pull/258). That may help to reduce the 250 MB.
